/* 
    1) FUNCTION WITHOUT A NAME.

    2) 'FUNCTION EXPRESSION': WHEN ANONYMOUS FUNCTION ASSIGNED TO A VARIABLE.
        // IN ORDER TO EXECUTE THE ANONYMOUS FUNCTION, WE WILL HAVE TO ASSIGN THAT FUNCTION INTO A VARIABLE.

    3) MOSTLY USED TO SET TIME INTERVAL : 'SetTimeout()' FUNCTION.

    4) SYNTAX OF SetTimeout() function:
        SetTimeout(FunctionName, Time in MiliSecond);

        (1000 MILISECOND = 1 SECOND)

    5) PARAMETER 1: NAME OF THE FUNCTION WHICH YOU WANT TO EXECUTE AFTER CERTAIN TIME INTERVAL:
    // THIS FUNCTION WOULD BE BE A NORMAL FUNCTION

    6) ANONYMOUS FUNCTION IS USED WHEN THE FUNCTION EXECUTES ONLY ONCE.
    7) ANONYMOUS FUNCTION IS USED WHEN WE HAVE IT PASS IT INTO THE PARAMETER OF ANOTHER FUNCTION ONLY ONCE.

    8) ANONYMOUS FUNCTION HELPS TO SAVE THE MEMORY AND FASTER EXECUTION.

*/

/* 
    function ()
    {
        document.write("Hello Anonymous user");
    } 
    ERROR: STATMENT REQUIRE A FUNCTION NAME
*/

/* 
    NORMAL FUNCTION CAN ALSO BE ASSIGNED TO A VARIABLE BUT IT WILL USELESS BECAUSE YOU ARE ALREADY GIVING A NAME TO A FUNCTION THEN NO NEED TO ASSIGN FUNCTION TO A VARIABLE AND CALL IT USING THE NAME OF A VARIABLE.

    EX: let temp1 = function abc()
        {
            alert("Hello Anonymous user");
        };
        //THIS IS ALSO VALID APPROACH:

    temp1(); // CALLING FUNCTION WITH THE NAME OF A VARIABLE.
*/


/* 
STORED ANONYMOUS FUNCTION INTO A VARIABLE AND CALL THAT FUNCTION USING THE NAME OF A VARIABLE.

THIS IS FUNCTION EXPRESSION: ASSIGNED ANONYMOUS FUNCTION TO VARIABLE.
    let temp = function ()
    {
        alert("Hello Anonymous user");
    };

    temp(); 
*/

// TIME INTERVAL USING SETTIMEOUT() FUNCTION
/* 
    THIS IS VALID APPROCH BUT WHEN YOU DECLARE THE NAME OF A FUNCTION INTO FIRST ARGUMENT OF SETTIMEOUT() FUNCTION, THEN IT WILL SAVE THE NAME AND ADDRESS OF THAT FUNCTION INTO MEMOERY AND WHEN THAT FUNCTION EXCUTE, IT WILL REMOVE THE NAME AND ADRESS BOTH FROM RAM.

    EX: function TimeDemo()
        {
            alert("Hello");
        }
        setTimeout(TimeDemo, 3000);
 */

// SOLUTION: USE ANONYMOUS FUNCTION INSTEAD OF NORMAL FUNCTION:


/* 
THIS IS ANONYMOUS FUNCTION AND INSTEAD OF STORING IT INTO A VARIABLE, WE CAN DEFINE IT INSIDE THE ARGUMENT OF SETTIMEOUT() FUNCTION.

    function () // ERROR: STATMENT MISSING FUNCTION NAME
    {
        alert("hello");
    } 
*/

setTimeout(function ()
    {
        alert("hello")
    },
     3000);