/* 
     1) WHEN WE WANT TO GENERATE RANDOM NUMBER THEN WE HAVE TO USE 'RANDOM METHOD' OF INBUILT 'OBJECT MATH OF JAVASCRIPT.

        EX: MATH.RANDOM();
    
     BY DEFAULT, THIS METHOD PROVIDES RANDOM NUMBER BETWEEN 0 TO 1 INCLUDING DECIMAL PART.

     2) IN ORDER TO SHIFT ONE DECIMAL RIGHT, WE HAVE TO MULTIPLY     RANDOM NUMBER BY 10.  (FOR LETF- DIVIDE)
     => IT WILL DISPLAY RANDOM NUMBER FROM 0 TO 9 (0 INCLUDED)
     (NOT 10)
     => CODE WILL GENERATE 'X-1' NUMBER, IF YOU MULTIPLY BY 'X'.
     => IF YOU WANT TO INCLUDE THE 'X' NUMBER ALSO IN RANDOM NUMBER THEN ADD IT BY '+1'. (X-1) (+1) = X

     3) IN ORDER TO AVOID THE DECIMAL (FRACTION PART) OF THE NUMBER, WE HAVE TO USE 'FLOOR METHOD' OF 'MATH OBJECT'.

     4) IF YOU WANT RANDOM NUMBER BETWEEN SPECIFIC RANGE
        EX: FROM 40 TO 96
        HERE MIN: 40 AND MAX: 96

        FORMULA = (MAX - MIN) + MIN;
        IN THIS, MIN WILL BE INCLUDED.

     5) IF YOU WANT TO INCLUDE MAX NUMBER ALSO, THEN ADD (MIN + 1)

*/

// let x = Math.floor(Math.random() * (56 - 40 + 1) + 40);
// console.log(x);


function genRandom(min , max){
   
   // MIN AND MAX BOTH ARE INCLUDED
    let x = Math.floor(Math.random() * (max - min + 1) + min); 
    return x; // RETURN OTP
}

// 6 DIGIT OTP Generator
let otp = genRandom(111111, 999999)
console.log(otp);