
/*
    THERE ARE 6 TYPES OF DATA TYPE IN JAVASCRIPT.
    1) NUMBER
    2) STRING
    3) BOOLEAN
    4) ARRAY
    5) OBJECT
    6) UNDEFINED
*/


/* 
    1) WE CAN CHANGE THE DATATYPE IN JAVASCRIPT (DYNAMIC VARIABLE)

    EX: LET A = 5; //NUMBER
        A = "NEHAL"; // STRING
        A = TRUE; // BOOLEAN

    2)(STRING DATATYPE) SINGLE AND DOUBLE QUOTATION IN STRING
    EX: LET A = 'NEHAL'; // SINGLE
        LET B = "NEHAL"; // DOUBLE

        IF WE WANT SINGLE QUOTE IN STRING USING SINGLE QUOTATION THEN IT WILL NOT WORK; (IF WE WANT NEH'HAL IN SINGLE QUOTE)
        EX: LET A = 'NEH'HAL'; // IT WILL NOT WORK;

        ==> IN THIS CASE, WE WILL HAVE TO USE DOUBLE QUOTE TO REPRESENT SINGLE QOUTE IN STRING
        EX: LET A = "NEH'AL"; // IT WILL WORK;

        ==> WHEN WE WANT DOUBLE QUOTE IN OUR STWING (NEH"AL);
            THEN WE WILL USE SINGLE QUOTATION TO REPRESENT DOUBLE QUOTE
            EX: LET A = 'NEH"AL'; // IT WILL WORK

        IF WE WANT DOUBLE QUOTATION IN OUR STRING USING DOUBLE QUOTATION;
        ("NEH"AL") THEN USE 'BACK SLASH' BEFORE MIDDLE DOUBLE QUOTE;
        EX: LET A = "NEH\"AL"; // IT WILL WORK AS NEH"AL
        
        (IT WILL SAME WITH SINGLE QUOTE ALSO)
        EX: LET A = 'NEH\'AL'; // IT WILL WORK AS NEH'AL

*/
 

/*
    ------- NUMBER DATA TYPE ------

    1) LET A = 10; // NUMBER
    2) LET A = 10.23; // NUMBER
    3) LET A = -10.2233; // NUMBER

    ALL ARE NUMBERS. NO DIFFERENCE
    (WHEN NUMBER ADD WITH STEING, IT WILL BECOME STRING
        EX: LET A = 5; //NUMBER
            LET B = '5' // STRING
            RESULT => 55 // STRING )
*/

/*
    ---- BOOLEAN ---- TRUE [1] OR FALSE [0] ----------
    
        LET A = TRUE;
        LET B = FALSE;

        IF( 3>2 ){ 
            ALERT(TRUE); // IT WILL RETURN 1
        }ELSE{
            ALERT(FALSE); // IT WILL RETURN 0
        }

*/


/* 
    ------------ ARRAY ----------
    => IT IS USED TO STORE MULTIPLE VALUES IN A SINGLE VARIABLE.
    => THESE VALUE COULD BE DIFFERENT AT THE SAME TIME.
    => THERE IS NO NEED TO STORE ONLY NUMBER OR ONLY STRING AT THE SAME TIME.

    EX: LET B = ['A','B','C']; // ARRAY OF STRINGS

    EX: LET B = [1,2,3,4]; // ARRAY OF NUMBERS

    EX: LET A = [1, 'HELLO', TRUE] ; // ARRAY WITH  DIFFERENT TYPES OF VALUES

*/

/*
 ----------- OBJECT [KEY : VALUE PAIR]------------

    LET PERSON = {  NAME : 'NEHAL', 
                    AGE : 20,
                    NUMBER : 9090909
                }
*/


/* 
    ------- UNDEFINED -------
    => DECLARE VARIABLE WITHOUT ANY VALUE WILL BE UNDEFINED

    EX: LET A;

*/
