/* 
    1) IMPORTANT TOPIC FOR INTERVIEW PERSPECTIVE.

    2) DEBUGGING IS USUALLY DONE WITH THE HELP OF THIS CONCEPT.
    
    3) WE CAN INDETIFY THE REASON OF AN ERROR USING THIS CONCEPT.

    4) HOISTING IS ONLY WORK WITH 'VAR' NOT 'LET' & 'CONST'.

    //THIS IS DEFAULT NATURE OF JAVASCRIPT.
    5) ONLY DECLARATION WILL BE HOISTED ON THE TOP BY THE COMPILER.
    (DECLARATION WITH INITIALIZATION WILL ALSO NOT WORK.)
    
    6) IT WILL HOIST ACCORDING TO ITS SCOPE.
    => GLOBAL THINGS WILL BE PULLED ON THE TOP OF THE 'FILE'.
    => LOCAL THINGS WILL BE PULLED ON THE TOP OF THE 'SCOPE',   
    NOT THE FILE. (FUNCTION SCOPE/ BLOCKS { ... })

    7) IN 'VAR': VAR X; 
    => IT WILL AUTOMATICALL INITIALIZE X = UNDEFINDED;

    BUT IN LET: LET X;
    => IT WILL NOT AUTOMATICALLY INITIALIZE X = UNDEFINED; THAT IS WHY THE ERROR COME THAT 'A' IS USED BEFORE INITIALIZE.

<--------------------------------------------------------------->

HOISTING MEANS : "TO LIFT" OR "TO PULL" (KHICHNA OR UTHANA) 
=> PULL OR LIFT ON THE TOP OF THE FILE.

IN OTHER PROGRAMMING LANGUAGE, IF PROGRAM EXECUTION REACHES DECLARATION AFTER ITS USE AND CALL, IT WILL DISPLAY AN ERROR.

EX:
    temp(); // function call

    // FUNCTION DECLARATION IS AFTER FUNCTION CALL.

    function temp() // function declaration
    {
        console.log("Hello");
    }

(IN JAVA, IT IS VALID AND PRINT HELLO IN CONSOLE)
----

IN JAVASCRIPT, IT "AUTOMATICALLY PULL" ALL THE DECLARATION AT THE BEGINING OF THE FILE AND AFTER IT WILL CALL OR USE IT.

THAT IS WHY JAVASCRIPT ALLOW FUNCTION DECLARATION AFTER FUNCTION CALL.

EX:
    // THIS DECLARATION PULLED BY JAVASCRIPT COMPILER

    function temp() // function declaration
    {
        console.log("Hello");
    }

    temp() // function call

*/

// HOISTING IN FUNCTION

temp(); // function call

function temp() // function declaration
{
    console.log("hello");
}


// ---------------------------------------------------------

// ONLY DECLARATION WILL BE HOISTED ON THE TOP.
// ONLY WORK WITH 'VAR', NOT 'LET' & 'CONST'.
// HOISTING IN VARIABLE.
// VARIABLE INITIALIZARION IS MUST BEFORE ACCESS USING 'LET'.

/* 
    let number; 
    DECLARATION IN JAVASCRIPT: let number = undefined;
 */

a = 10; // INITIALIZATION

alert(a); // CALL | IT WILL DISPLAY 10 | VALID

// THIS WILL PULL ON THE TOP OF THE PAGE BY JAVASCRIPT COMPILER
var a; // DECLARATION 