"use strict" // STRICT MODE: ON

x = 10; // INITIALIZATION WITHOUT DECLARATION

console.log(x); // NO ERROR. WITHOUT DECLARATION OF VARIABLE.

/*

1) JAVASCRIPT WILL AUTOMATICALL DECLARE THE VARIABLE BY ITSELF.

2) var x = undefined; ON THE TOP

3) BUT THIS WOULD BE THE REASON OF THE BUGG IN PROGRAMMING THAT IS WHY WE ALWAYS NEED TO ENSURE AND PREFER 'STRICT MODE', AND SHOUL NOT ALLOW ANYBODY TO USE IT WITHOUT 'STRICT MODE'. 

*/

/* ----------- */

// ERROR: X IS NOT DEFINED

// MEANS IT WILL NOT AUTOMATICALLY DECLARE THE VARIABLE BY ITSELF WHEN WE USE "USE STRICT" MODE.