/*

1) DOUNLE EQUAL TO (==) IS ONLY CHECK THE VALUE, IT IGNORES DATA TYPE

EX: 5 == 5; // TRUE
    5 == 6; // FALSE
    5 == '5'; // TRUE => IGNORE DATA TYPE


2) TRIPLE EQUAL TO WILL COMPARE BOTH; VALUE AND DATA TYPE

EX: 5 === 5; //TRUE
    5 === 6; // FALSE
    5 === '5' // FALSE => FIRST CHECK 'DATA TYPE' AND THEN 'NUMBER' 

3) NOT EQUAL TO (ONLY CHECK THE VALUE; IGNORE DATA TYPE)

EX: 5 != 5; // FALSE
    5 != 6; // TRUE
    5 != '5'; //FALSE

4) NOT DOUBLE EQUAL T0 (FIRST CHECK TYPE AND THEN VALUE)
=> OPPOSITE OF EQUAL TO

EX: 5 !== 5; // FALSE
    5 !== 6; // TRUE
    5 !== '5'; // TRUE

*/