// TURNARY OPERATOR IS ONLY USED WHEN THERE IS A SMALL CONDITION TO CHECK AND ASSIGNMENT INTO A VARIABLE.

// WHEN THERE IS MORE THAN TWO OR THREE LINES THEN USE IF ELSE CONDITION.

// SYNTAX:: CONDITION ? IF BLOCK : ELSE BLOCK;

let isLoggedIn = 0;

let option = isLoggedIn ? "LogIn" : "Logout";

alert(option);