// NULLISH COALESCING OPERATOR

// WHEN USER IS LOGGED IN [IsLoggedIn = 1] THEN IT ASSIGN THE NAME OF USER AND WILL PRINT THE NAME OF THE USER.

// WHEN USER IS NOT LOGGED IN [IsLoggedIn = 0] THEN IT WILL BY DEFAULT PRINT 'UNDEFINED' BECAUSE WE ARE NOT ASSIGNING THE NAME OF USER TO A VARIABLE(USER)
    // IN THIS CASE, WE USE NULLISH COALESCING OPERATOR TO ASSIGN THE TEMPORARY NAME TO USER VARIABLE USING (?? "STRING").

    let isLoggedIn = prompt("enter 1 or 0"); // 1 FOR LOGGED IN AND 0 FOR LOGGED OUT
    let user;
    
    if(isLoggedIn){
        user = "Nehal Panchal"; // ONLY WHEN USER IS LOGGED-IN
        alert(user);
    }else{
        alert(user ?? "Guest User.");
    }